Pin python3.11. Include geopyspark for better tests.

diff --git a/OpenEO_Dockerfile b/OpenEO_Dockerfile
--- a/OpenEO_Dockerfile
+++ b/OpenEO_Dockerfile
@@ -17,10 +17,10 @@ RUN apt-get -qq update && \
         bc \
         nano \
         wget \
-        python3-pip \
         curl \
         parallel \
-        dpkg && \
+        dpkg \
+        software-properties-common && \
     rm -rf /var/lib/apt/lists/*
 
 # Download and install jacksum and s5cmd
@@ -41,13 +41,12 @@ ENV AWS_S3_ENDPOINT=eodata.dataspace.copernicus.eu \
 
 
 
-### Install esa-snap ###
+RUN add-apt-repository -y ppa:deadsnakes/ppa
 RUN apt-get -qq update && \
     apt-get -qq install -y \
       build-essential \
       git \
-      python3 \
-      python3-venv \
+      python3.11 python3.11-distutils python3.11-dev python3.11-venv \
       cmake \
       autoconf \
       libgfortran5
@@ -55,6 +54,7 @@ RUN apt-get -qq update && \
 LABEL authors="Michele Claus, Emile Sonneveld"
 LABEL maintainer="michele.claus@eurac.edu, emile.sonneveld@vito.be"
 
+### Install esa-snap ###
 ENV SNAPVER=11
 
 RUN mkdir -p /src/esa-snap-docker
@@ -76,7 +76,7 @@ COPY cwl/ /src/cwl/
 COPY pyproject.toml /src/pyproject.toml
 # . /opt/venv/bin/activate -> has no effect in Docker, here we need the following line:
 ENV PATH="/opt/venv/bin:$PATH"
-RUN python3 -m venv /opt/venv && \
+RUN python3.11 -m venv /opt/venv && \
     cd /src && \
     python3 -m pip install -q . && \
     python3 -m pip install -q --config-settings="--build-option=build_ext" --config-settings="--build-option=-I/usr/include/gdal" GDAL==`gdal-config --version`
@@ -88,13 +88,23 @@ RUN cd /opt && \
     cd stac-catalog-builder && \
     python3 -m pip install -q -e .
 
-# for testing:
+# For testing: TODO: Checkout specific commit
 RUN cd /opt && \
     git clone --recursive https://github.com/Open-EO/openeo-geopyspark-driver --depth 1 && \
-    python3 -m pip install setuptools==64 && echo "setuptools to fix jep" && \
     cd /opt/openeo-geopyspark-driver && \
     git pull && git submodule update --init --recursive && \
-    python3 -m pip install -e .[dev] --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple
+    sed -i '/jep==/ s/^/# /' setup.py && \
+    echo "ok" && \
+
+# First install fails, ignore this:
+RUN cd /opt/openeo-geopyspark-driver && \
+    python3 -m pip install -e . --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple || echo "Command failed, but ignored"
+
+# TODO: Make get-jars available as package script, so not the whole repo needs to be downloaded
+RUN cd /opt/openeo-geopyspark-driver && \
+python3 -m pip install -e . --extra-index-url https://artifactory.vgt.vito.be/api/pypi/python-openeo/simple && \
+    python scripts/get-jars.py --force-download jars && \
+    echo "openeo-geopyspark-driver installed for testing"
 
 RUN wget https://step.esa.int/thirdparties/snaphu/1.4.2-2/snaphu-v1.4.2_linux.zip && unzip -q -d / snaphu-v1.4.2_linux.zip
 ENV PATH="$PATH:/snaphu-v1.4.2_linux/bin"
